/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class cbforest {
  public static byte[] cdata(SWIGTYPE_p_void ptr, int nelements) {
    return cbforestJNI.cdata(SWIGTYPE_p_void.getCPtr(ptr), nelements);
  }

  public static void memmove(SWIGTYPE_p_void data, byte[] indata) {
    cbforestJNI.memmove(SWIGTYPE_p_void.getCPtr(data), indata);
  }

}
