/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class Collatable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Collatable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Collatable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_Collatable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Collatable() {
    this(cbforestJNI.new_Collatable__SWIG_0(), true);
  }

  public Collatable(boolean v) {
    this(cbforestJNI.new_Collatable__SWIG_1(v), true);
  }

  public Collatable(double v) {
    this(cbforestJNI.new_Collatable__SWIG_2(v), true);
  }

  public Collatable(String v) {
    this(cbforestJNI.new_Collatable__SWIG_3(v), true);
  }

  public Collatable(Collatable v) {
    this(cbforestJNI.new_Collatable__SWIG_4(Collatable.getCPtr(v), v), true);
  }

  public Collatable(Slice v) {
    this(cbforestJNI.new_Collatable__SWIG_5(Slice.getCPtr(v), v), true);
  }

  public Collatable addNull() {
    long cPtr = cbforestJNI.Collatable_addNull(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable add(boolean arg0) {
    long cPtr = cbforestJNI.Collatable_add__SWIG_0(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable add(double arg0) {
    long cPtr = cbforestJNI.Collatable_add__SWIG_1(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable add(Collatable arg0) {
    long cPtr = cbforestJNI.Collatable_add__SWIG_2(swigCPtr, this, Collatable.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable add(String arg0) {
    long cPtr = cbforestJNI.Collatable_add__SWIG_3(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable add(Slice arg0) {
    long cPtr = cbforestJNI.Collatable_add__SWIG_4(swigCPtr, this, Slice.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable beginArray() {
    long cPtr = cbforestJNI.Collatable_beginArray(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable endArray() {
    long cPtr = cbforestJNI.Collatable_endArray(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable beginMap() {
    long cPtr = cbforestJNI.Collatable_beginMap(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable endMap() {
    long cPtr = cbforestJNI.Collatable_endMap(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Collatable addSpecial() {
    long cPtr = cbforestJNI.Collatable_addSpecial(swigCPtr, this);
    return (cPtr == 0) ? null : new Collatable(cPtr, false);
  }

  public Slice toSlice() {
    long cPtr = cbforestJNI.Collatable_toSlice(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public long size() {
    return cbforestJNI.Collatable_size(swigCPtr, this);
  }

  public boolean empty() {
    return cbforestJNI.Collatable_empty(swigCPtr, this);
  }

  public String dump() {
    return cbforestJNI.Collatable_dump(swigCPtr, this);
  }

}
