/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class CollatableTypes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CollatableTypes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CollatableTypes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_CollatableTypes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CollatableTypes() {
    this(cbforestJNI.new_CollatableTypes(), true);
  }

  public final static class Tag {
    public final static CollatableTypes.Tag kEndSequence = new CollatableTypes.Tag("kEndSequence", cbforestJNI.CollatableTypes_kEndSequence_get());
    public final static CollatableTypes.Tag kNull = new CollatableTypes.Tag("kNull");
    public final static CollatableTypes.Tag kFalse = new CollatableTypes.Tag("kFalse");
    public final static CollatableTypes.Tag kTrue = new CollatableTypes.Tag("kTrue");
    public final static CollatableTypes.Tag kNegative = new CollatableTypes.Tag("kNegative");
    public final static CollatableTypes.Tag kPositive = new CollatableTypes.Tag("kPositive");
    public final static CollatableTypes.Tag kString = new CollatableTypes.Tag("kString");
    public final static CollatableTypes.Tag kArray = new CollatableTypes.Tag("kArray");
    public final static CollatableTypes.Tag kMap = new CollatableTypes.Tag("kMap");
    public final static CollatableTypes.Tag kSpecial = new CollatableTypes.Tag("kSpecial");
    public final static CollatableTypes.Tag kError = new CollatableTypes.Tag("kError", cbforestJNI.CollatableTypes_kError_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Tag swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Tag.class + " with value " + swigValue);
    }

    private Tag(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Tag(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Tag(String swigName, Tag swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Tag[] swigValues = { kEndSequence, kNull, kFalse, kTrue, kNegative, kPositive, kString, kArray, kMap, kSpecial, kError };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
