/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public final class ContentOptions {
  public final static ContentOptions kDefaultContent = new ContentOptions("kDefaultContent", cbforestJNI.kDefaultContent_get());
  public final static ContentOptions kMetaOnly = new ContentOptions("kMetaOnly", cbforestJNI.kMetaOnly_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ContentOptions swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ContentOptions.class + " with value " + swigValue);
  }

  private ContentOptions(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ContentOptions(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ContentOptions(String swigName, ContentOptions swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ContentOptions[] swigValues = { kDefaultContent, kMetaOnly };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

