/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class Database extends KeyStore {
  private transient long swigCPtr;

  protected Database(long cPtr, boolean cMemoryOwn) {
    super(cbforestJNI.Database_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Database obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_Database(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Config defaultConfig() {
    return new Config(cbforestJNI.Database_defaultConfig(), true);
  }

  public Database(String path, Config cfg) throws java.lang.Exception {
    this(cbforestJNI.new_Database(path, Config.getCPtr(cfg), cfg), true);
  }

  public FileInfo getFileInfo() throws java.lang.Exception {
    return new FileInfo(cbforestJNI.Database_getFileInfo(swigCPtr, this), true);
  }

  public String getFilename() {
    return cbforestJNI.Database_getFilename(swigCPtr, this);
  }

  public boolean isReadOnly() {
    return cbforestJNI.Database_isReadOnly(swigCPtr, this);
  }

  public void deleteDatabase() {
    cbforestJNI.Database_deleteDatabase(swigCPtr, this);
  }

  public void erase() {
    cbforestJNI.Database_erase(swigCPtr, this);
  }

  public void compact() throws java.lang.Exception {
    cbforestJNI.Database_compact(swigCPtr, this);
  }

  public void commit() throws java.lang.Exception {
    cbforestJNI.Database_commit(swigCPtr, this);
  }

}
