/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class Document {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Document(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_Document(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Document() {
    this(cbforestJNI.new_Document__SWIG_0(), true);
  }

  public Document(Slice key) {
    this(cbforestJNI.new_Document__SWIG_1(Slice.getCPtr(key), key), true);
  }

  public Slice getKey() {
    long cPtr = cbforestJNI.Document_getKey(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public Slice getMeta() {
    long cPtr = cbforestJNI.Document_getMeta(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public Slice getBody() {
    long cPtr = cbforestJNI.Document_getBody(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public void setKey(Slice key) {
    cbforestJNI.Document_setKey(swigCPtr, this, Slice.getCPtr(key), key);
  }

  public void setMeta(Slice meta) {
    cbforestJNI.Document_setMeta(swigCPtr, this, Slice.getCPtr(meta), meta);
  }

  public void setBody(Slice body) {
    cbforestJNI.Document_setBody(swigCPtr, this, Slice.getCPtr(body), body);
  }

  public Slice resizeMeta(long newSize) throws java.lang.Exception {
    long cPtr = cbforestJNI.Document_resizeMeta(swigCPtr, this, newSize);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public void clearMetaAndBody() {
    cbforestJNI.Document_clearMetaAndBody(swigCPtr, this);
  }

  public java.math.BigInteger getSequence() {
    return cbforestJNI.Document_getSequence(swigCPtr, this);
  }

  public java.math.BigInteger offset() {
    return cbforestJNI.Document_offset(swigCPtr, this);
  }

  public long sizeOnDisk() {
    return cbforestJNI.Document_sizeOnDisk(swigCPtr, this);
  }

  public boolean deleted() {
    return cbforestJNI.Document_deleted(swigCPtr, this);
  }

  public boolean exists() {
    return cbforestJNI.Document_exists(swigCPtr, this);
  }

  public boolean valid() {
    return cbforestJNI.Document_valid(swigCPtr, this);
  }

  public void updateSequence(java.math.BigInteger s) {
    cbforestJNI.Document_updateSequence(swigCPtr, this, s);
  }

}
