/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class FileInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_FileInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FileInfo() {
    this(cbforestJNI.new_FileInfo(), true);
  }

  public String getFilename() {
    return cbforestJNI.FileInfo_getFilename(swigCPtr, this);
  }

  public String getNewFilename() {
    return cbforestJNI.FileInfo_getNewFilename(swigCPtr, this);
  }

  public java.math.BigInteger getDocCount() {
    return cbforestJNI.FileInfo_getDocCount(swigCPtr, this);
  }

  public java.math.BigInteger getSpaceUsed() {
    return cbforestJNI.FileInfo_getSpaceUsed(swigCPtr, this);
  }

  public java.math.BigInteger getFileSize() {
    return cbforestJNI.FileInfo_getFileSize(swigCPtr, this);
  }

}
