/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class IndexWriter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_IndexWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexWriter(Index index, Transaction t) {
    this(cbforestJNI.new_IndexWriter(Index.getCPtr(index), index, Transaction.getCPtr(t), t), true);
  }

  public boolean update(Slice arg0, java.math.BigInteger arg1, VectorCollatable arg2, VectorCollatable arg3) {
    return cbforestJNI.IndexWriter_update(swigCPtr, this, Slice.getCPtr(arg0), arg0, arg1, VectorCollatable.getCPtr(arg2), arg2, VectorCollatable.getCPtr(arg3), arg3);
  }

  public java.math.BigInteger getRowCount() {
    return cbforestJNI.IndexWriter_getRowCount(swigCPtr, this);
  }

  public void setRowCount(java.math.BigInteger arg0) {
    cbforestJNI.IndexWriter_setRowCount(swigCPtr, this, arg0);
  }

}
