/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class IndexEnumerator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexEnumerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexEnumerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_IndexEnumerator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexEnumerator(Index arg0, Collatable arg1, Slice arg2, Collatable arg3, Slice arg4, DocEnumerator.Options options) {
    this(cbforestJNI.new_IndexEnumerator__SWIG_0(Index.getCPtr(arg0), arg0, Collatable.getCPtr(arg1), arg1, Slice.getCPtr(arg2), arg2, Collatable.getCPtr(arg3), arg3, Slice.getCPtr(arg4), arg4, DocEnumerator.Options.getCPtr(options), options), true);
  }

  public IndexEnumerator(Index arg0, VectorKeyRange keyRanges, DocEnumerator.Options options) {
    this(cbforestJNI.new_IndexEnumerator__SWIG_1(Index.getCPtr(arg0), arg0, VectorKeyRange.getCPtr(keyRanges), keyRanges, DocEnumerator.Options.getCPtr(options), options), true);
  }

  public CollatableReader key() {
    long cPtr = cbforestJNI.IndexEnumerator_key(swigCPtr, this);
    return (cPtr == 0) ? null : new CollatableReader(cPtr, false);
  }

  public CollatableReader value() {
    long cPtr = cbforestJNI.IndexEnumerator_value(swigCPtr, this);
    return (cPtr == 0) ? null : new CollatableReader(cPtr, false);
  }

  public Slice docID() {
    long cPtr = cbforestJNI.IndexEnumerator_docID(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public java.math.BigInteger sequence() {
    return cbforestJNI.IndexEnumerator_sequence(swigCPtr, this);
  }

  public boolean next() throws java.lang.Exception {
    return cbforestJNI.IndexEnumerator_next(swigCPtr, this);
  }

}
