/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class MapFn {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MapFn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapFn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_MapFn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    cbforestJNI.MapFn_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    cbforestJNI.MapFn_change_ownership(this, swigCPtr, true);
  }

  public void call(Mappable arg0, EmitFn emit) {
    if (getClass() == MapFn.class) cbforestJNI.MapFn_call(swigCPtr, this, Mappable.getCPtr(arg0), arg0, EmitFn.getCPtr(emit), emit); else cbforestJNI.MapFn_callSwigExplicitMapFn(swigCPtr, this, Mappable.getCPtr(arg0), arg0, EmitFn.getCPtr(emit), emit);
  }

  public MapFn() {
    this(cbforestJNI.new_MapFn(), true);
    cbforestJNI.MapFn_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
