/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class MapReduceIndex extends Index {
  private transient long swigCPtr;

  protected MapReduceIndex(long cPtr, boolean cMemoryOwn) {
    super(cbforestJNI.MapReduceIndex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapReduceIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_MapReduceIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MapReduceIndex(Database arg0, String arg1, KeyStore arg2) {
    this(cbforestJNI.new_MapReduceIndex(Database.getCPtr(arg0), arg0, arg1, KeyStore.getCPtr(arg2), arg2), true);
  }

  public KeyStore sourceStore() {
    long cPtr = cbforestJNI.MapReduceIndex_sourceStore(swigCPtr, this);
    return (cPtr == 0) ? null : new KeyStore(cPtr, false);
  }

  public void readState() {
    cbforestJNI.MapReduceIndex_readState(swigCPtr, this);
  }

  public int indexType() {
    return cbforestJNI.MapReduceIndex_indexType(swigCPtr, this);
  }

  public void setup(Transaction arg0, int arg1, MapFn arg2, String arg3) {
    cbforestJNI.MapReduceIndex_setup(swigCPtr, this, Transaction.getCPtr(arg0), arg0, arg1, MapFn.getCPtr(arg2), arg2, arg3);
  }

  public java.math.BigInteger lastSequenceIndexed() {
    return cbforestJNI.MapReduceIndex_lastSequenceIndexed(swigCPtr, this);
  }

  public java.math.BigInteger lastSequenceChangedAt() {
    return cbforestJNI.MapReduceIndex_lastSequenceChangedAt(swigCPtr, this);
  }

  public java.math.BigInteger rowCount() {
    return cbforestJNI.MapReduceIndex_rowCount(swigCPtr, this);
  }

  public void erase(Transaction arg0) {
    cbforestJNI.MapReduceIndex_erase(swigCPtr, this, Transaction.getCPtr(arg0), arg0);
  }

}
