/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class MapReduceIndexer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MapReduceIndexer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapReduceIndexer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_MapReduceIndexer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    cbforestJNI.MapReduceIndexer_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    cbforestJNI.MapReduceIndexer_change_ownership(this, swigCPtr, true);
  }

  public MapReduceIndexer() {
    this(cbforestJNI.new_MapReduceIndexer(), true);
    cbforestJNI.MapReduceIndexer_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void addIndex(MapReduceIndex arg0, Transaction arg1) {
    cbforestJNI.MapReduceIndexer_addIndex(swigCPtr, this, MapReduceIndex.getCPtr(arg0), arg0, Transaction.getCPtr(arg1), arg1);
  }

  public void triggerOnIndex(MapReduceIndex arg0) {
    cbforestJNI.MapReduceIndexer_triggerOnIndex(swigCPtr, this, MapReduceIndex.getCPtr(arg0), arg0);
  }

  public boolean run() {
    return cbforestJNI.MapReduceIndexer_run(swigCPtr, this);
  }

  public void addDocument(Document arg0) {
    if (getClass() == MapReduceIndexer.class) cbforestJNI.MapReduceIndexer_addDocument(swigCPtr, this, Document.getCPtr(arg0), arg0); else cbforestJNI.MapReduceIndexer_addDocumentSwigExplicitMapReduceIndexer(swigCPtr, this, Document.getCPtr(arg0), arg0);
  }

  public void addMappable(Mappable arg0) {
    cbforestJNI.MapReduceIndexer_addMappable(swigCPtr, this, Mappable.getCPtr(arg0), arg0);
  }

}
