/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public final class OpenFlags {
  public final static OpenFlags FDB_OPEN_FLAG_CREATE = new OpenFlags("FDB_OPEN_FLAG_CREATE", cbforestJNI.FDB_OPEN_FLAG_CREATE_get());
  public final static OpenFlags FDB_OPEN_FLAG_RDONLY = new OpenFlags("FDB_OPEN_FLAG_RDONLY", cbforestJNI.FDB_OPEN_FLAG_RDONLY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OpenFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OpenFlags.class + " with value " + swigValue);
  }

  private OpenFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OpenFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OpenFlags(String swigName, OpenFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OpenFlags[] swigValues = { FDB_OPEN_FLAG_CREATE, FDB_OPEN_FLAG_RDONLY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

