/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class RevID extends Slice {
  private transient long swigCPtr;

  protected RevID(long cPtr, boolean cMemoryOwn) {
    super(cbforestJNI.RevID_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_RevID(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RevID() {
    this(cbforestJNI.new_RevID__SWIG_0(), true);
  }

  public RevID(String arg0, long arg1) {
    this(cbforestJNI.new_RevID__SWIG_1(arg0, arg1), true);
  }

  public RevID(String arg0) {
    this(cbforestJNI.new_RevID__SWIG_2(arg0), true);
  }

  public boolean isCompressed() {
    return cbforestJNI.RevID_isCompressed(swigCPtr, this);
  }

  public Slice expanded() {
    long cPtr = cbforestJNI.RevID_expanded(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public long expandedSize() {
    return cbforestJNI.RevID_expandedSize(swigCPtr, this);
  }

  public boolean expandInto(Slice dst) {
    return cbforestJNI.RevID_expandInto(swigCPtr, this, Slice.getCPtr(dst), dst);
  }

  public long generation() throws java.lang.Exception {
    return cbforestJNI.RevID_generation(swigCPtr, this);
  }

  public Slice digest() throws java.lang.Exception {
    long cPtr = cbforestJNI.RevID_digest(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public byte[] getBuf() {
    return cbforestJNI.RevID_getBuf(swigCPtr, this);
  }

  public String toString() {
    return cbforestJNI.RevID_toString(swigCPtr, this);
  }

  public long getBufSize() {
    return cbforestJNI.RevID_getBufSize(swigCPtr, this);
  }

}
