/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class Revision {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Revision(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Revision obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_Revision(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Revision() {
    this(cbforestJNI.new_Revision(), true);
  }

  public RevTree getOwner() {
    long cPtr = cbforestJNI.Revision_getOwner(swigCPtr, this);
    return (cPtr == 0) ? null : new RevTree(cPtr, false);
  }

  public RevID getRevID() {
    long cPtr = cbforestJNI.Revision_getRevID(swigCPtr, this);
    return (cPtr == 0) ? null : new RevID(cPtr, false);
  }

  public java.math.BigInteger getSequence() {
    return cbforestJNI.Revision_getSequence(swigCPtr, this);
  }

  public boolean isBodyAvailable() {
    return cbforestJNI.Revision_isBodyAvailable(swigCPtr, this);
  }

  public Slice readBody() {
    long cPtr = cbforestJNI.Revision_readBody(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public boolean isLeaf() {
    return cbforestJNI.Revision_isLeaf(swigCPtr, this);
  }

  public boolean isDeleted() {
    return cbforestJNI.Revision_isDeleted(swigCPtr, this);
  }

  public boolean hasAttachments() {
    return cbforestJNI.Revision_hasAttachments(swigCPtr, this);
  }

  public boolean isNew() {
    return cbforestJNI.Revision_isNew(swigCPtr, this);
  }

  public boolean isActive() {
    return cbforestJNI.Revision_isActive(swigCPtr, this);
  }

  public long index() {
    return cbforestJNI.Revision_index(swigCPtr, this);
  }

  public Revision getParent() {
    long cPtr = cbforestJNI.Revision_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new Revision(cPtr, false);
  }

  public VectorRevision history() {
    return new VectorRevision(cbforestJNI.Revision_history(swigCPtr, this), true);
  }

  public boolean isSameAddress(Revision arg0) {
    return cbforestJNI.Revision_isSameAddress(swigCPtr, this, Revision.getCPtr(arg0), arg0);
  }

}
