/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class RevIDBuffer extends RevID {
  private transient long swigCPtr;

  protected RevIDBuffer(long cPtr, boolean cMemoryOwn) {
    super(cbforestJNI.RevIDBuffer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevIDBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_RevIDBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RevIDBuffer() {
    this(cbforestJNI.new_RevIDBuffer__SWIG_0(), true);
  }

  public RevIDBuffer(Slice arg0) {
    this(cbforestJNI.new_RevIDBuffer__SWIG_1(Slice.getCPtr(arg0), arg0), true);
  }

  public void parse(Slice arg0) throws java.lang.Exception {
    cbforestJNI.RevIDBuffer_parse(swigCPtr, this, Slice.getCPtr(arg0), arg0);
  }

}
