/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class VectorRevID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorRevID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorRevID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_VectorRevID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorRevID() {
    this(cbforestJNI.new_VectorRevID__SWIG_0(), true);
  }

  public VectorRevID(long n) {
    this(cbforestJNI.new_VectorRevID__SWIG_1(n), true);
  }

  public long size() {
    return cbforestJNI.VectorRevID_size(swigCPtr, this);
  }

  public long capacity() {
    return cbforestJNI.VectorRevID_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    cbforestJNI.VectorRevID_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return cbforestJNI.VectorRevID_isEmpty(swigCPtr, this);
  }

  public void clear() {
    cbforestJNI.VectorRevID_clear(swigCPtr, this);
  }

  public void add(RevID x) {
    cbforestJNI.VectorRevID_add(swigCPtr, this, RevID.getCPtr(x), x);
  }

  public RevID get(int i) {
    long cPtr = cbforestJNI.VectorRevID_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new RevID(cPtr, false);
  }

  public void set(int i, RevID val) {
    cbforestJNI.VectorRevID_set(swigCPtr, this, i, RevID.getCPtr(val), val);
  }

}
