/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class VectorMapReduceIndex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorMapReduceIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorMapReduceIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_VectorMapReduceIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorMapReduceIndex() {
    this(cbforestJNI.new_VectorMapReduceIndex__SWIG_0(), true);
  }

  public VectorMapReduceIndex(long n) {
    this(cbforestJNI.new_VectorMapReduceIndex__SWIG_1(n), true);
  }

  public long size() {
    return cbforestJNI.VectorMapReduceIndex_size(swigCPtr, this);
  }

  public long capacity() {
    return cbforestJNI.VectorMapReduceIndex_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    cbforestJNI.VectorMapReduceIndex_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return cbforestJNI.VectorMapReduceIndex_isEmpty(swigCPtr, this);
  }

  public void clear() {
    cbforestJNI.VectorMapReduceIndex_clear(swigCPtr, this);
  }

  public void add(MapReduceIndex x) {
    cbforestJNI.VectorMapReduceIndex_add(swigCPtr, this, MapReduceIndex.getCPtr(x), x);
  }

  public MapReduceIndex get(int i) {
    long cPtr = cbforestJNI.VectorMapReduceIndex_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MapReduceIndex(cPtr, false);
  }

  public void set(int i, MapReduceIndex val) {
    cbforestJNI.VectorMapReduceIndex_set(swigCPtr, this, i, MapReduceIndex.getCPtr(val), val);
  }

}
