/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class VectorCollatable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorCollatable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorCollatable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_VectorCollatable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorCollatable() {
    this(cbforestJNI.new_VectorCollatable__SWIG_0(), true);
  }

  public VectorCollatable(long n) {
    this(cbforestJNI.new_VectorCollatable__SWIG_1(n), true);
  }

  public long size() {
    return cbforestJNI.VectorCollatable_size(swigCPtr, this);
  }

  public long capacity() {
    return cbforestJNI.VectorCollatable_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    cbforestJNI.VectorCollatable_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return cbforestJNI.VectorCollatable_isEmpty(swigCPtr, this);
  }

  public void clear() {
    cbforestJNI.VectorCollatable_clear(swigCPtr, this);
  }

  public void add(Collatable x) {
    cbforestJNI.VectorCollatable_add(swigCPtr, this, Collatable.getCPtr(x), x);
  }

  public Collatable get(int i) {
    return new Collatable(cbforestJNI.VectorCollatable_get(swigCPtr, this, i), false);
  }

  public void set(int i, Collatable val) {
    cbforestJNI.VectorCollatable_set(swigCPtr, this, i, Collatable.getCPtr(val), val);
  }

}
