/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class VectorKeyRange {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorKeyRange(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorKeyRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_VectorKeyRange(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorKeyRange() {
    this(cbforestJNI.new_VectorKeyRange__SWIG_0(), true);
  }

  public VectorKeyRange(long n) {
    this(cbforestJNI.new_VectorKeyRange__SWIG_1(n), true);
  }

  public long size() {
    return cbforestJNI.VectorKeyRange_size(swigCPtr, this);
  }

  public long capacity() {
    return cbforestJNI.VectorKeyRange_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    cbforestJNI.VectorKeyRange_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return cbforestJNI.VectorKeyRange_isEmpty(swigCPtr, this);
  }

  public void clear() {
    cbforestJNI.VectorKeyRange_clear(swigCPtr, this);
  }

  public void add(KeyRange x) {
    cbforestJNI.VectorKeyRange_add(swigCPtr, this, KeyRange.getCPtr(x), x);
  }

  public KeyRange get(int i) {
    long cPtr = cbforestJNI.VectorKeyRange_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new KeyRange(cPtr, false);
  }

  public void set(int i, KeyRange val) {
    cbforestJNI.VectorKeyRange_set(swigCPtr, this, i, KeyRange.getCPtr(val), val);
  }

}
