/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class VectorRevision {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorRevision(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorRevision obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_VectorRevision(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorRevision() {
    this(cbforestJNI.new_VectorRevision__SWIG_0(), true);
  }

  public VectorRevision(long n) {
    this(cbforestJNI.new_VectorRevision__SWIG_1(n), true);
  }

  public long size() {
    return cbforestJNI.VectorRevision_size(swigCPtr, this);
  }

  public long capacity() {
    return cbforestJNI.VectorRevision_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    cbforestJNI.VectorRevision_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return cbforestJNI.VectorRevision_isEmpty(swigCPtr, this);
  }

  public void clear() {
    cbforestJNI.VectorRevision_clear(swigCPtr, this);
  }

  public void add(Revision x) {
    cbforestJNI.VectorRevision_add(swigCPtr, this, Revision.getCPtr(x), x);
  }

  public Revision get(int i) {
    long cPtr = cbforestJNI.VectorRevision_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Revision(cPtr, false);
  }

  public void set(int i, Revision val) {
    cbforestJNI.VectorRevision_set(swigCPtr, this, i, Revision.getCPtr(val), val);
  }

}
